[tool.poetry]
name = "alarm"
version = "0.1.0"
description = ""
authors = ["Bob Belderbos <bobbelderbos@gmail.com>"]
license = "MIT"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.7"
playsound = "^1.2"
python-decouple = "^3.3"
pyobjc = "^7.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8 = "^3.8.4"
mypy = "^0.790"
black = {version = "^20.8b1", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
alarm = "alarm.alarm:main"
